#!/bin/bash
#SBATCH -J TOPAS_Job
#SBATCH --partition=mediumq
#SBATCH --time=02:00:00
#SBATCH -o %x-%j.out
#SBATCH -e %x-%j.err

# Charger le module TOPAS
module load topas

# Préparer le répertoire de travail
export WORK_DIR=/data/$USER/TOPAS_${SLURM_JOB_ID}
export INPUT_DIR=$PWD/Input

[[ -z $INPUT_DIR ]] && { echo "Error: Input Directory (INPUT_DIR) is not defined "; exit 1; }
[[ ! -d $INPUT_DIR ]] && { echo "Error: Input Directory (INPUT_DIR) does not exist "; exit 1; }

mkdir -p $WORK_DIR
cp -R $INPUT_DIR/* $WORK_DIR

cd $WORK_DIR

echo "Running TOPAS at $WORK_DIR"

topas Dose.txt

echo "Done"
